[package]
name = "euler"
version = "0.1.0"
authors = ["Michael Bryan <michaelfbryan@gmail.com>"]
description = "Solutions to some of the Euler Challenges using Rust."

[dependencies]
env_logger = "*"
log = "*"
regex = "*"
ansi_term = "*"
cake = "*"
time = "0.1"
clap = "*"
num = "*"
rayon = "*"
